<?php

/**
 * Catálogo de los 50 parámetros de adaptación por perfil de aprendizaje.
 * Extraído de pednia_admin_condiciones_v3_1.html (BASE, PRESETS_F, CATS, PRINCIPIOS).
 * Valores guardados por perfil → storage/app/parametros-perfil/{tipo}/{id}.json
 */
return [
    'mapa_perfiles' => [
        1 => 'estandar',
        2 => 'tdah',
        3 => 'tea',
        4 => 'down',
        5 => 'disc_visual',
        6 => 'disc_auditiva',
        7 => 'disc_motriz',
        8 => 'disc_intelectual',
    ],

    'principios' => [
        'estandar' => 'Accesibilidad universal',
        'tea' => 'Predictibilidad y control sensorial',
        'tdah' => 'Refuerzo frecuente e inmediato',
        'disc_visual' => 'Audio como canal principal',
        'disc_auditiva' => 'Visual como canal principal',
        'disc_motriz' => 'Sin precisión fina',
        'down' => 'Máxima simplificación',
        'disc_intelectual' => 'Reducción de carga cognitiva',
    ],

    'base' => [
        'btn_size' => 72,
        'btn_spacing' => 12,
        'font_size' => 16,
        'lectura_facil' => false,
        'subtitulos' => false,
        'trans_ms' => 300,
        'anim_speed' => 100,
        'anim_decorativas' => true,
        'audio_instruc' => 'opcional',
        'audio_fondo' => true,
        'audio_btn' => true,
        'gestos' => 'toque y swipe',
        'auto_avance' => false,
        'cooperativo' => false,
        'opciones_max' => 4,
        'intentos_max' => 3,
        'refuerzo' => 'al completar',
        'progreso' => 'barra',
        'ra_inicio' => 'automático',
        'ra_velocidad' => 100,
        'ra_contenido' => 'animación',
        'contraste' => 'estándar',
        'modo_color' => 'normal',
        'fondo_pantalla' => 'blanco',
        'elementos_flotantes' => true,
        'cursor_grande' => false,
        'refuerzo_visual' => true,
        'refuerzo_sonido' => true,
        'refuerzo_tipo' => 'animación',
        'error_visible' => true,
        'feedback_demora_ms' => 400,
        'tiempo_max_bloque' => 0,
        'pausa_entre_bloques' => false,
        'duracion_pausa_seg' => 5,
        'recordatorio_postura' => false,
        'idioma' => 'español',
        'voz_narradora' => 'infantil_femenina',
        'velocidad_voz' => 100,
        'repeticion_audio' => false,
        'grosor_pincel' => 6,
        'paleta_reducida' => false,
        'deshacer' => true,
        'lienzo_cuadriculado' => false,
        'rompecabezas_piezas_max' => 9,
        'memoria_pares_max' => 6,
        'secuencia_pasos_max' => 4,
        'juego_bordes' => false,
        'login_tipo' => 'pin_4',
        'teclado_grande' => false,
        'modo_aula_automatico' => false,
    ],

    'presets' => [
        'estandar' => [],
        'tea' => [
            'btn_size' => 80,
            'trans_ms' => 150,
            'anim_speed' => 50,
            'anim_decorativas' => false,
            'elementos_flotantes' => false,
            'audio_instruc' => 'manual',
            'audio_fondo' => false,
            'audio_btn' => false,
            'opciones_max' => 2,
            'refuerzo' => 'cada paso',
            'progreso' => 'pasos',
            'ra_inicio' => 'manual',
            'ra_velocidad' => 50,
            'gestos' => 'solo toque',
            'contraste' => 'estándar',
            'fondo_pantalla' => 'crema',
            'refuerzo_visual' => false,
            'refuerzo_sonido' => false,
            'refuerzo_tipo' => 'badge',
            'error_visible' => false,
            'feedback_demora_ms' => 0,
            'pausa_entre_bloques' => true,
            'duracion_pausa_seg' => 5,
            'paleta_reducida' => true,
            'deshacer' => false,
            'rompecabezas_piezas_max' => 4,
            'memoria_pares_max' => 2,
            'secuencia_pasos_max' => 2,
            'login_tipo' => 'avatar',
        ],
        'tdah' => [
            'trans_ms' => 200,
            'refuerzo' => 'cada 2 pasos',
            'progreso' => 'barra prominente',
            'intentos_max' => 5,
            'fondo_pantalla' => 'crema',
            'elementos_flotantes' => false,
            'tiempo_max_bloque' => 60,
            'feedback_demora_ms' => 0,
            'refuerzo_visual' => true,
            'refuerzo_sonido' => false,
        ],
        'disc_visual' => [
            'btn_size' => 88,
            'font_size' => 22,
            'audio_instruc' => 'automático',
            'subtitulos' => true,
            'ra_contenido' => 'audio narrado',
            'opciones_max' => 2,
            'contraste' => 'máximo',
            'cursor_grande' => true,
            'fondo_pantalla' => 'gris_suave',
            'voz_narradora' => 'lenta',
            'velocidad_voz' => 85,
            'repeticion_audio' => true,
            'grosor_pincel' => 14,
            'lienzo_cuadriculado' => true,
            'juego_bordes' => true,
            'teclado_grande' => true,
        ],
        'disc_auditiva' => [
            'audio_instruc' => 'desactivado',
            'audio_fondo' => false,
            'audio_btn' => false,
            'subtitulos' => true,
            'ra_contenido' => 'video LSC',
            'contraste' => 'alto',
            'refuerzo_visual' => true,
            'refuerzo_sonido' => false,
            'refuerzo_tipo' => 'animación',
        ],
        'disc_motriz' => [
            'btn_size' => 96,
            'btn_spacing' => 20,
            'gestos' => 'solo toque',
            'cooperativo' => true,
            'cursor_grande' => true,
            'grosor_pincel' => 16,
            'lienzo_cuadriculado' => true,
            'teclado_grande' => true,
            'login_tipo' => 'avatar',
        ],
        'down' => [
            'btn_size' => 88,
            'font_size' => 18,
            'trans_ms' => 400,
            'anim_speed' => 50,
            'opciones_max' => 2,
            'refuerzo' => 'cada paso',
            'progreso' => 'círculos',
            'lectura_facil' => true,
            'ra_inicio' => 'manual',
            'ra_velocidad' => 50,
            'cooperativo' => true,
            'contraste' => 'alto',
            'fondo_pantalla' => 'crema',
            'elementos_flotantes' => false,
            'voz_narradora' => 'muy_lenta',
            'velocidad_voz' => 70,
            'repeticion_audio' => true,
            'refuerzo_tipo' => 'badge',
            'error_visible' => false,
            'pausa_entre_bloques' => true,
            'rompecabezas_piezas_max' => 4,
            'memoria_pares_max' => 2,
            'secuencia_pasos_max' => 2,
            'paleta_reducida' => true,
            'login_tipo' => 'pin_3',
        ],
        'disc_intelectual' => [
            'btn_size' => 88,
            'font_size' => 18,
            'trans_ms' => 350,
            'anim_speed' => 75,
            'anim_decorativas' => false,
            'elementos_flotantes' => false,
            'audio_instruc' => 'automático',
            'opciones_max' => 2,
            'refuerzo' => 'cada paso',
            'progreso' => 'círculos',
            'lectura_facil' => true,
            'ra_inicio' => 'manual',
            'ra_velocidad' => 75,
            'ra_contenido' => 'animación + narración',
            'cooperativo' => true,
            'intentos_max' => 5,
            'contraste' => 'alto',
            'fondo_pantalla' => 'crema',
            'voz_narradora' => 'lenta',
            'velocidad_voz' => 80,
            'repeticion_audio' => true,
            'refuerzo_tipo' => 'badge',
            'error_visible' => false,
            'pausa_entre_bloques' => true,
            'paleta_reducida' => true,
            'rompecabezas_piezas_max' => 4,
            'memoria_pares_max' => 2,
            'secuencia_pasos_max' => 2,
        ],
    ],

    'categorias' => [
        [
            'k' => 'botones',
            'label' => 'Botones',
            'icon' => 'fa-hand-pointer',
            'params' => [
                ['k' => 'btn_size', 'icon' => 'fa-expand', 'label' => 'Tamaño de botón', 'desc' => 'Área táctil mínima en píxeles', 'type' => 'num', 'min' => 72, 'max' => 120, 'step' => 4, 'unit' => 'px'],
                ['k' => 'btn_spacing', 'icon' => 'fa-arrows-left-right', 'label' => 'Espacio entre botones', 'desc' => 'Margen entre elementos táctiles', 'type' => 'num', 'min' => 8, 'max' => 28, 'step' => 2, 'unit' => 'px'],
            ],
        ],
        [
            'k' => 'tipografia',
            'label' => 'Tipografía',
            'icon' => 'fa-font',
            'params' => [
                ['k' => 'font_size', 'icon' => 'fa-text-height', 'label' => 'Tamaño de fuente', 'desc' => 'Tamaño del texto de instrucciones', 'type' => 'num', 'min' => 14, 'max' => 26, 'step' => 2, 'unit' => 'pt'],
                ['k' => 'lectura_facil', 'icon' => 'fa-book-open-reader', 'label' => 'Lectura fácil', 'desc' => 'Instrucciones con máximo 3 palabras', 'type' => 'toggle'],
                ['k' => 'subtitulos', 'icon' => 'fa-closed-captioning', 'label' => 'Subtítulos en video', 'desc' => 'Activa subtítulos en todos los videos', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'audio',
            'label' => 'Audio',
            'icon' => 'fa-volume-high',
            'params' => [
                ['k' => 'audio_instruc', 'icon' => 'fa-microphone-lines', 'label' => 'Audio de instrucción', 'desc' => 'Cómo se reproduce al iniciar el bloque', 'type' => 'select', 'opts' => ['opcional', 'manual', 'automático', 'desactivado']],
                ['k' => 'audio_fondo', 'icon' => 'fa-music', 'label' => 'Audio de fondo', 'desc' => 'Música ambiental del ambiente', 'type' => 'toggle'],
                ['k' => 'audio_btn', 'icon' => 'fa-bell', 'label' => 'Sonido en botones', 'desc' => 'Retroalimentación sonora al tocar', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'animaciones',
            'label' => 'Animaciones',
            'icon' => 'fa-film',
            'params' => [
                ['k' => 'trans_ms', 'icon' => 'fa-clock', 'label' => 'Duración transición', 'desc' => 'Velocidad entre pantallas en ms', 'type' => 'num', 'min' => 100, 'max' => 600, 'step' => 50, 'unit' => 'ms'],
                ['k' => 'anim_speed', 'icon' => 'fa-gauge-high', 'label' => 'Velocidad animaciones', 'desc' => '100% normal · 50% mitad', 'type' => 'num', 'min' => 25, 'max' => 100, 'step' => 25, 'unit' => '%'],
                ['k' => 'anim_decorativas', 'icon' => 'fa-wand-magic-sparkles', 'label' => 'Animaciones decorativas', 'desc' => 'Elementos animados de fondo', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'navegacion',
            'label' => 'Navegación',
            'icon' => 'fa-compass',
            'params' => [
                ['k' => 'gestos', 'icon' => 'fa-hand', 'label' => 'Gestos habilitados', 'desc' => 'Tipos de interacción táctil', 'type' => 'select', 'opts' => ['toque y swipe', 'solo toque']],
                ['k' => 'auto_avance', 'icon' => 'fa-forward', 'label' => 'Auto-avance', 'desc' => 'Avance automático al completar bloque', 'type' => 'toggle'],
                ['k' => 'cooperativo', 'icon' => 'fa-users', 'label' => 'Modo cooperativo', 'desc' => 'El docente participa junto al niño', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'evaluacion',
            'label' => 'Evaluación',
            'icon' => 'fa-clipboard-check',
            'params' => [
                ['k' => 'opciones_max', 'icon' => 'fa-list-ol', 'label' => 'Opciones máximas', 'desc' => 'Alternativas en bloques de selección', 'type' => 'num', 'min' => 2, 'max' => 6, 'step' => 1, 'unit' => 'opc.'],
                ['k' => 'intentos_max', 'icon' => 'fa-rotate-right', 'label' => 'Intentos permitidos', 'desc' => 'Antes de mostrar la respuesta', 'type' => 'num', 'min' => 1, 'max' => 5, 'step' => 1, 'unit' => 'int.'],
                ['k' => 'refuerzo', 'icon' => 'fa-star', 'label' => 'Frecuencia refuerzo', 'desc' => 'Cuándo aparece la celebración', 'type' => 'select', 'opts' => ['al completar', 'cada 2 pasos', 'cada paso']],
                ['k' => 'progreso', 'icon' => 'fa-bars-progress', 'label' => 'Indicador de progreso', 'desc' => 'Cómo se muestra el avance', 'type' => 'select', 'opts' => ['barra', 'barra prominente', 'pasos', 'círculos']],
            ],
        ],
        [
            'k' => 'ra',
            'label' => 'RA',
            'icon' => 'fa-cube',
            'params' => [
                ['k' => 'ra_inicio', 'icon' => 'fa-camera', 'label' => 'Inicio RA', 'desc' => 'Cómo se activa al detectar el marcador', 'type' => 'select', 'opts' => ['automático', 'manual']],
                ['k' => 'ra_velocidad', 'icon' => 'fa-gauge', 'label' => 'Velocidad RA', 'desc' => '100% normal · 50% mitad', 'type' => 'num', 'min' => 25, 'max' => 100, 'step' => 25, 'unit' => '%'],
                ['k' => 'ra_contenido', 'icon' => 'fa-vr-cardboard', 'label' => 'Contenido RA', 'desc' => 'Qué muestra al detectar el marcador', 'type' => 'select', 'opts' => ['animación', 'audio narrado', 'video LSC', 'animación + narración']],
            ],
        ],
        [
            'k' => 'contraste',
            'label' => 'Contraste',
            'icon' => 'fa-circle-half-stroke',
            'params' => [
                ['k' => 'contraste', 'icon' => 'fa-sun', 'label' => 'Nivel de contraste', 'desc' => 'Diferencia visual entre elementos y fondo', 'type' => 'select', 'opts' => ['estándar', 'alto', 'máximo']],
                ['k' => 'modo_color', 'icon' => 'fa-palette', 'label' => 'Modo de color', 'desc' => 'Ajuste para alteraciones en la percepción cromática', 'type' => 'select', 'opts' => ['normal', 'daltonismo_protanopia', 'daltonismo_deuteranopia', 'escala_grises']],
                ['k' => 'fondo_pantalla', 'icon' => 'fa-fill-drip', 'label' => 'Color de fondo', 'desc' => 'Fondo de las pantallas de la tablet', 'type' => 'select', 'opts' => ['blanco', 'crema', 'gris_suave']],
                ['k' => 'elementos_flotantes', 'icon' => 'fa-cloud', 'label' => 'Elementos flotantes', 'desc' => 'Partículas y objetos animados de fondo · desactivar ayuda en TEA y TDAH', 'type' => 'toggle'],
                ['k' => 'cursor_grande', 'icon' => 'fa-arrow-pointer', 'label' => 'Cursor grande', 'desc' => 'Indicador de toque visible y ampliado · útil en disc. motriz y visual', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'retroalimentacion',
            'label' => 'Retroalimentación',
            'icon' => 'fa-comment-dots',
            'params' => [
                ['k' => 'refuerzo_visual', 'icon' => 'fa-sparkles', 'label' => 'Refuerzo visual', 'desc' => 'Confeti, brillos y animaciones al completar un bloque', 'type' => 'toggle'],
                ['k' => 'refuerzo_sonido', 'icon' => 'fa-volume-high', 'label' => 'Sonido de recompensa', 'desc' => 'Fanfarria y efectos de sonido al recibir la recompensa', 'type' => 'toggle'],
                ['k' => 'refuerzo_tipo', 'icon' => 'fa-trophy', 'label' => 'Tipo de refuerzo', 'desc' => 'Qué tipo de recompensa ve el niño al completar', 'type' => 'select', 'opts' => ['animación', 'badge', 'solo_texto', 'trofeo_estático']],
                ['k' => 'error_visible', 'icon' => 'fa-circle-exclamation', 'label' => 'Mensaje de error visible', 'desc' => 'Mostrar texto cuando el niño responde incorrectamente · desactivar en TEA evita crisis', 'type' => 'toggle'],
                ['k' => 'feedback_demora_ms', 'icon' => 'fa-hourglass-half', 'label' => 'Demora del feedback (ms)', 'desc' => '0ms = instantáneo · 400ms = breve pausa antes de mostrar la retroalimentación', 'type' => 'num', 'min' => 0, 'max' => 1500, 'step' => 100, 'unit' => 'ms'],
            ],
        ],
        [
            'k' => 'sesion',
            'label' => 'Sesión',
            'icon' => 'fa-stopwatch',
            'params' => [
                ['k' => 'tiempo_max_bloque', 'icon' => 'fa-clock-rotate-left', 'label' => 'Tiempo máx por bloque (seg)', 'desc' => '0 = sin límite · 30–120 seg = límite por bloque, avanza automáticamente al agotarse', 'type' => 'num', 'min' => 0, 'max' => 120, 'step' => 10, 'unit' => 'seg'],
                ['k' => 'pausa_entre_bloques', 'icon' => 'fa-pause', 'label' => 'Pausa entre bloques', 'desc' => 'Pantalla de descanso entre cada bloque · ayuda a niños con TEA a regular', 'type' => 'toggle'],
                ['k' => 'duracion_pausa_seg', 'icon' => 'fa-hourglass', 'label' => 'Duración de la pausa (seg)', 'desc' => 'Cuántos segundos dura la pantalla de pausa entre bloques', 'type' => 'num', 'min' => 3, 'max' => 10, 'step' => 1, 'unit' => 'seg'],
                ['k' => 'recordatorio_postura', 'icon' => 'fa-chair', 'label' => 'Recordatorio de postura', 'desc' => 'Notificación al docente cada 10 minutos para verificar posición del niño', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'idioma',
            'label' => 'Idioma',
            'icon' => 'fa-language',
            'params' => [
                ['k' => 'idioma', 'icon' => 'fa-globe', 'label' => 'Idioma de instrucciones', 'desc' => 'Idioma en que se narran las instrucciones de audio', 'type' => 'select', 'opts' => ['español', 'wayuunaiki', 'inglés']],
                ['k' => 'voz_narradora', 'icon' => 'fa-headphones', 'label' => 'Voz narradora', 'desc' => 'Estilo y ritmo de la voz que lee las instrucciones en la tablet', 'type' => 'select', 'opts' => ['infantil_femenina', 'infantil_masculina', 'lenta', 'muy_lenta']],
                ['k' => 'velocidad_voz', 'icon' => 'fa-gauge-simple', 'label' => 'Velocidad de voz', 'desc' => '100% = velocidad normal · 70% = muy lenta, ideal para Down', 'type' => 'num', 'min' => 60, 'max' => 120, 'step' => 5, 'unit' => '%'],
                ['k' => 'repeticion_audio', 'icon' => 'fa-repeat', 'label' => 'Repetición automática', 'desc' => 'Reproducir la instrucción de audio 2 veces automáticamente al entrar a cada bloque', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'dibujo',
            'label' => 'Dibujo',
            'icon' => 'fa-paintbrush',
            'params' => [
                ['k' => 'grosor_pincel', 'icon' => 'fa-pencil', 'label' => 'Grosor del pincel', 'desc' => 'Trazo grueso compensa imprecisión motriz fina · 6px normal · 14–16px disc. motriz', 'type' => 'num', 'min' => 4, 'max' => 20, 'step' => 2, 'unit' => 'px'],
                ['k' => 'paleta_reducida', 'icon' => 'fa-swatchbook', 'label' => 'Paleta reducida', 'desc' => 'Mostrar solo 3–4 colores · evita parálisis de decisión en TEA y Down', 'type' => 'toggle'],
                ['k' => 'deshacer', 'icon' => 'fa-rotate-left', 'label' => 'Botón deshacer', 'desc' => 'El niño puede borrar el último trazo · desactivar en TEA evita bucles de ansiedad', 'type' => 'toggle'],
                ['k' => 'lienzo_cuadriculado', 'icon' => 'fa-border-all', 'label' => 'Lienzo cuadriculado', 'desc' => 'Mostrar cuadrícula de guía en el canvas · ayuda en disc. motriz para referencia espacial', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'juegos',
            'label' => 'Juegos',
            'icon' => 'fa-gamepad',
            'params' => [
                ['k' => 'rompecabezas_piezas_max', 'icon' => 'fa-puzzle-piece', 'label' => 'Rompecabezas — piezas máx', 'desc' => 'Limita la dificultad máxima aunque el docente configure más piezas · 4=fácil, 9=normal', 'type' => 'num', 'min' => 4, 'max' => 9, 'step' => 1, 'unit' => 'piezas'],
                ['k' => 'memoria_pares_max', 'icon' => 'fa-clone', 'label' => 'Memoria — pares máx', 'desc' => 'Limita el número de pares visibles · 2–3 para Down y disc. intelectual', 'type' => 'num', 'min' => 2, 'max' => 6, 'step' => 1, 'unit' => 'pares'],
                ['k' => 'secuencia_pasos_max', 'icon' => 'fa-list-check', 'label' => 'Secuencia — pasos máx', 'desc' => 'Limita los pasos visibles en el juego de secuencias', 'type' => 'num', 'min' => 2, 'max' => 4, 'step' => 1, 'unit' => 'pasos'],
                ['k' => 'juego_bordes', 'icon' => 'fa-square', 'label' => 'Bordes destacados en juegos', 'desc' => 'Bordes gruesos en piezas y tarjetas · ayuda en disc. visual baja y daltonismo', 'type' => 'toggle'],
            ],
        ],
        [
            'k' => 'acceso',
            'label' => 'Acceso',
            'icon' => 'fa-right-to-bracket',
            'params' => [
                ['k' => 'login_tipo', 'icon' => 'fa-key', 'label' => 'Tipo de inicio de sesión', 'desc' => 'Cómo ingresa el niño a la app en la tablet', 'type' => 'select', 'opts' => ['pin_4', 'pin_3', 'avatar', 'docente_inicia']],
                ['k' => 'teclado_grande', 'icon' => 'fa-keyboard', 'label' => 'Teclado grande', 'desc' => 'Botones del teclado PIN más grandes · disc. motriz y niños de 3 años con Down', 'type' => 'toggle'],
                ['k' => 'modo_aula_automatico', 'icon' => 'fa-chalkboard-user', 'label' => 'Modo Aula automático', 'desc' => 'Al hacer login va directo a la experiencia del día sin menús · el docente la configura previamente', 'type' => 'toggle'],
            ],
        ],
    ],
];
